ESS Web Application/ViewModels/LeaveApplicationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ESS_Web_Application.ViewModels
{
    public class LeaveApplicationViewModel
    {
        public bool isResumeDuty { get; set; }

        public string RefNo { get; set; }
        public string LeaveType { get; set; }
        public string RequestDate { get; set; }
        public string Employee { get; set; }
        public string Approver { get; set; }
        public string ReqStatus { get; set; }
        public string EmployeeId { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string NoofDays { get; set; }
        public string Leavebalance { get; set; }
        public string Remarks { get; set; }
        public bool IsEditViisible { get; set; }
        public bool isSubmitVisible { get; set; }
        public bool isRecallVisible { get; set; }
        public bool isCompletedVisible { get; set; }
        public bool isInProcessVisible { get; set; }
        public string ReplacementEmployee { get; set; }
        public string CalendarDays { get; set; }
        public string Description { get; set; }
        public string AttachmentGuid { get; set; }
        public string RequestID { get; set; }
        public string CompanyName { get; set; }
    }
    public class LeaveApplicationListViewModel
    {
        public LeaveApplicationListViewModel()
        {
            History = new List<LeaveApplicationViewModel>();
            Approval = new List<LeaveApplicationViewModel>();
        }
        public bool IsApproval { get; set; }
        public string ProfileImage { get; set; }
        public List<LeaveApplicationViewModel> History { get; set; }
        public List<LeaveApplicationViewModel> Approval { get; set; }
    }

    public class EmployeeDetailRequestViewModel
    {
        public string RefNo { get; set; }
        public string RequestDate { get; set; }
        public string Employee { get; set; }
        public string ReqStatus { get; set; }
        public string EmployeeId { get; set; }
        public string ContactDetail { get; set; }
        public string LastName { get; set; }
        public string Description { get; set; }
        public string MatrialStatus { get; set; }
        public string EmployeeAddress { get; set; }
        public bool IsEditViisible { get; set; }
        public bool isSubmitVisible { get; set; }
        public bool isRecallVisible { get; set; }
        public bool isCompletedVisible { get; set; }
        public bool isInProcessVisible { get; set; }
        public string History { get; set; }
        public string Approver { get; internal set; }
        public string ApprovedBy { get; internal set; }
        public string AttachmentGuid { get; set; }
        public string RequestId { get; set; }
        public string CompanyName { get; set; }
        public string DEPRTMNT { get; set; }
        public string DESIGNATION { get; set; }
    }
    public class EmployeeDetailRequestListViewModel
    {
        public EmployeeDetailRequestListViewModel()
        {
            History = new List<EmployeeDetailRequestViewModel>();
            Approval = new List<EmployeeDetailRequestViewModel>();
        }
        public bool IsApproval { get; set; }
        public string ProfileImage { get; set; }
        public List<EmployeeDetailRequestViewModel> History { get; set; }
        public List<EmployeeDetailRequestViewModel> Approval { get; set; }
    }
}

ESS Web Application/ViewModels/StaffExpenseViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ESS_Web_Application.ViewModels
{
    public class StaffExpenseViewModel
    {
        public string Ref { get; set; }
        public string RequestDate { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string Remarks { get; set; }
    }
}

ESS Web Application/ViewModels/TicketRequestViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ESS_Web_Application.ViewModels
{
    public class TicketRequestViewModel
    {
        public string RefNo { get; set; }
        public string RequestDate { get; set; }
        public string Employee { get; set; }
        public string ReqStatus { get; set; }
        public string EmployeeId { get; set; }
        public string TicketType { get; set; }
        public string TicketBalance { get; set; }
        public string Remarks { get; set; }
        public bool IsEditViisible { get; set; }
        public bool isSubmitVisible { get; set; }
        public bool isRecallVisible { get; set; }
        public bool isCompletedVisible { get; set; }
        public bool isInProcessVisible { get; set; }
        public string TravelFrom { get; set; }
        public string TravelTo { get; set; }
        public string DateReturn { get; set; }
        public string DateTravel { get; set; }
        public string TravelFromCountry { get; set; }
        public string TravelToCountry { get; set; }
        public string History { get; set; }
        public string Description { get; set; }
        public string Approver { get; set; }
        public string ApprovedBy { get; set; }
        public string AttachmentGuid { get; set; }
        public string RequestID { get; set; }
        public string CompanyName { get; set; }
    }
    public class TicketRequestListViewModel
    {
        public TicketRequestListViewModel()
        {
            History = new List<TicketRequestViewModel>();
            Approval = new List<TicketRequestViewModel>();
        }
        public bool IsApproval { get; set; }
        public List<TicketRequestViewModel> History { get; set; }
        public List<TicketRequestViewModel> Approval { get; set; }
    }
}

ESS Web Application/Controllers/RequestController.cs
using ESS_Web_Application.Entity;
using ESS_Web_Application.Helper;
using ESS_Web_Application.Infrastructure;
using ESS_Web_Application.Services;
using ESS_Web_Application.ViewModels;
using Microsoft.Reporting.WebForms;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace ESS_Web_Application.Controllers
{
    [AuthorizeActionFilter]
    public class RequestController : Controller
    {
        IRequestService _requestService = new RequestService();
        // GET: Request
        [HttpPost]
        public ActionResult SaveProfileImage(string FormName)
        {
            try
            {
                if (System.Web.HttpContext.Current.Request.Files.AllKeys.Any())
                {
                    HttpFileCollectionBase files = Request.Files;

                    Guid guid = Guid.NewGuid();
                    for (int i = 0; i < files.Count; i++)
                    {
                        HttpPostedFileBase file = files[i];
                        string fname;
                        // Checking for Internet Explorer      
                        if (Request.Browser.Browser.ToUpper() == "IE" || Request.Browser.Browser.ToUpper() == "INTERNETEXPLORER")
                        {
                            string[] testfiles = file.FileName.Split(new char[] { '\\' });
                            fname = testfiles[testfiles.Length - 1];
                        }
                        else
                        {
                            fname = file.FileName;
                        }
                        var pic = System.Web.HttpContext.Current.Request.Files[fname];
                        HttpPostedFileBase filebase = new HttpPostedFileWrapper(pic);
                        UploadFiles.UploadFile(filebase, FormName, guid.ToString());
                    }
                    return Json(guid.ToString());
                }
                else
                {
                    return Json("No File Saved.");
                }
            }
            catch (Exception ex)
            {
                return Json("Error While Saving.");
            }
        }
        //[HttpPost]
        //[ValidateInput(false)]
        //public FileResult DownloadReport(string PrintId)
        //{
        //    DownloadDetails data = new DownloadDetails();
        //    if (!String.IsNullOrEmpty(PrintId))
        //    {
        //        data = UploadFiles.DownloadFile(PrintId);
        //    }

        //    return File(Encoding.ASCII.GetBytes(data.Bytes == null ? "" : data.Bytes.ToString()), data.ContentType == null ? "abac" : data.ContentType, data.Name == null ? "" : data.Name);
        //}
        [HttpPost]
        [ValidateInput(false)]
        public FileResult DownloadReport(FormCollection form)
        {
            string PrintId = form["DocName"].ToString();
            DownloadDetails data = new DownloadDetails();
            if (!String.IsNullOrEmpty(PrintId))
            {
                data = UploadFiles.DownloadFile(PrintId);
            }

            return File(Encoding.ASCII.GetBytes(data.Bytes == null ? "" : data.Bytes.ToString()), data.ContentType == null ? "abac" : data.ContentType, data.Name == null ? "" : data.Name);
        }
        public JsonResult LoadUploadedFiles(string DocType, string DocNumber)
        {
            string str = DocType;
            string str1 = DocNumber;
            DataTable fileList = GetFileList(str, str1);
            List<AttachmentModel> attch = new List<AttachmentModel>();
            if (fileList != null && fileList.Rows.Count > 0)
            {
                //double num = Convert.ToDouble(fileList.Compute("SUM(Size)", ""));
                //if (num > 0)
                //{
                // this.lblTotalSize.Text = this.CalculateFileSize(num);
                //}
                foreach (DataRow item in fileList.Rows)
                {
                    AttachmentModel att = new AttachmentModel()
                    {
                        ID = item["ID"].ToString(),
                        Name = item["Name"].ToString(),
                        Remarks = item["Remarks"].ToString(),
                        DOCID = item["DOCID"].ToString(),
                    };
                    attch.Add(att);
                }
            }
            return Json(attch);
        }

        public static DataTable GetFileList(string DocType, string DocID)
        {
            DataTable dataTable = new DataTable();
            using (SqlConnection sqlConnection = new SqlConnection())
            {
                sqlConnection.ConnectionString = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
                sqlConnection.Open();
                SqlCommand sqlCommand = new SqlCommand();
                sqlCommand.Connection = sqlConnection;
                sqlCommand.CommandTimeout = 0;
                sqlCommand.CommandText = "SELECT ID,DOCID, Name, ContentType, Size , Remarks FROM TBL_UploadFiles WHERE  DOCID = @DOCID AND DocType= @DocType";
                sqlCommand.Parameters.Add("@DOCID", SqlDbType.VarChar, 50);
                sqlCommand.Parameters.Add("@DocType", SqlDbType.VarChar, 50);
                sqlCommand.Parameters["@DOCID"].Value = DocID;
                sqlCommand.Parameters["@DocType"].Value = DocType;
                sqlCommand.CommandType = CommandType.Text;
                SqlDataAdapter sqlDataAdapter = new SqlDataAdapter();
                sqlDataAdapter.SelectCommand = sqlCommand;
                sqlDataAdapter.Fill(dataTable);
                sqlConnection.Close();
            }
            return dataTable;
        }

        #region LeaveApplication
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult LeaveApplicationForm()
        {
            if (string.IsNullOrEmpty(Session["UserName"].ToString()))
            {
                return RedirectToAction("Login", "Account");
            }
            if (clsCommon.ValidatePageSecurity(Session["UserName"].ToString(), "LeaveAppForm"))
            {
                ViewBag.User = _requestService.GetLeaveAppUsers(Session["UserID"].ToString(), "LeaveAppForm", Session["UserCompanyID"].ToString());
                ViewBag.LeaveTypes = _requestService.GetLeaveTypes(Session["UserID"].ToString());
                ViewBag.ReplacementEmployee = _requestService.GetReplacementEmployee(Session["UserCompanyID"].ToString());
                ViewBag.Countries = _requestService.GetCountries();
                return View();
            }
            else
            {
                return RedirectToAction("Dashboard", "Home");
            }
        }
        public JsonResult GetCities(string CountryId)
        {
            var data = _requestService.GetCities(CountryId);
            return Json(data);
        }
        public JsonResult GetEmployeeDetails(string SelectUserId)
        {
            var data = _requestService.GetEmployeeDeatils(SelectUserId);
            return Json(data);
        }
        public JsonResult GetEmployeeLeavesData(string EmployeeId, string LeaveTypeId, string StartDate, string EndDate, string LeaveType)
        {
            string Enddate = string.IsNullOrEmpty(EndDate) ? "" : DateTime.Parse(EndDate).Date.AddDays(-1).ToString();
            var data = _requestService.FillCalculatedFields(EmployeeId, LeaveTypeId, StartDate, Enddate, LeaveType);
            return Json(data);
        }
        public JsonResult SaveLeaveRequest(string AtchGuid, string EmployeeID, string LeaveType, string Remarks, string Airticket, string ReplacementId, string StartDate, string ReturnToWork, string LeaveTypeName, string Noofdays, string Leavebalance, string TravelTo, string TravelFrom, string DateofTravel, string DateofReturn, string Accomodation)
        {
            string Enddate = DateTime.Parse(ReturnToWork).Date.AddDays(-1).ToString();
            string data = _requestService.SaveLeaveRequest(AtchGuid, Session["UserCompanyID"].ToString(), EmployeeID, LeaveType, Remarks, Airticket, ReplacementId, StartDate, Enddate, ReturnToWork, LeaveTypeName, Session["UserID"].ToString(), Noofdays, Leavebalance, TravelTo, TravelFrom, DateofTravel, DateofReturn, Accomodation);
            return Json(data);
        }
        public JsonResult GetLeaveApplicationData(string EmpId)
        {
            var data = _requestService.GetLeaveApplicationData(EmpId, Session["UserID"].ToString(), Session["UserCompanyID"].ToString());
            byte[] bytes = GetImageFromDB(Session["UserID"].ToString());
            if (bytes.Length > 1)
            {
                string Profileimg = "data:image/jpeg;base64," + Convert.ToBase64String(bytes);
                data.ProfileImage = Profileimg;
            }
            return Json(data);
        }
        public JsonResult GetEmployeeLeavesEditData(string Id)
        {
            var data = _requestService.GetEmployeeLeavesEditData(Id);
            return Json(data);
        }
        public JsonResult SaveEditLeaveRequest(string Reqid, string EmployeeID, string LeaveType, string Remarks, string ReplacementId, string StartDate, string EndDate, string Noofdays, string Leavebalance)
        {
            string data = _requestService.SaveEditLeaveRequest(Reqid, EmployeeID, LeaveType, Remarks, ReplacementId, StartDate, EndDate, Session["UserID"].ToString(), Session["UserCompanyID"].ToString(), Noofdays, Leavebalance);
            return Json(data);
        }
        public ActionResult GetLeaveApproval(string Id)
        {
            var data = _requestService.GetLeaveApproval(Id);
            return Json(data);
        }

ESS Web Application/Views/Request/EmployeeAttendanceDetail.cshtml
@{
    ViewBag.Title = "EmployeeAttendanceDetail";
}

<div class="block-header">
    <div class="row">
        <div class="col-lg-6 col-md-8 col-sm-12">
            <h2><a href="javascript:void(0);" class="btn btn-xs btn-link btn-toggle-fullwidth"><i class="fa fa-arrow-left"></i></a> Dashboard</h2>
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html"><i class="icon-home"></i></a></li>
                <li class="breadcrumb-item active">Dashboard</li>
            </ul>
        </div>

    </div>
</div>
<div class="row">
    <div class="col-lg-12 col-md-12">
        <div class="card">
            <div class="header">
                <h2>Employee Attendance Details</h2>
            </div>
            <div class="body">
                <div class="table-responsive">
                    <div class="col-md-6 col-sm-12">
                        <label>Employee</label>
                        <div class="form-group">
                            <select id="Emp" class="form-control show-tick">
                                <option value="0">Select Employee</option>
                                @foreach (var item in ViewBag.User)
                                {
                                    if (item.Text == "Self")
                                    {
                                        <option selected value="@item.Value">@item.Text</option>
                                    }
                                    else
                                    {
                                        <option value="@item.Value">@item.Text</option>
                                    }
                                }
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <label>Start Date</label>
                        <input id="StartDate" type="text" data-provide="datepicker" data-date-autoclose="true" class="form-control" placeholder="From *">
                    </div>
                    <br />
                    <div class="col-md-6 col-sm-12">
                        <label>End Date</label>
                        <input id="EndDate" type="text" data-provide="datepicker" data-date-autoclose="true" class="form-control" placeholder="To *">
                    </div>
                    <br />
                    <div class="col-12">
                        <button onclick="Search()" type="submit" class="btn btn-primary">Generate Report</button>
                    </div>
                    <br />
                  
                </div>

            </div>
        </div>
    </div>
</div>
@using (Html.BeginForm("EmployeeAttendanceReport", "Request", FormMethod.Post, new { target = "_blank" }))
{
    <input type="hidden" id="employeeId" name="EmpId" />
    <input type="hidden" id="txtStartsate" name="StartDate" />
    <input type="hidden" id="txtEndDate" name="EndDate" />
    <input type="submit" class="hidden" id="btnSubmit" hidden value="Export" />
}
<script>
    function Search() {
        if ($("#Emp").val() != undefined && $("#Emp").val() != null && $("#StartDate").val() != undefined && $("#StartDate").val() != null && $("#EndDate").val() != undefined && $("#EndDate").val() != null) {
            $("#employeeId").val($("#Emp").val());
            $("#txtStartsate").val($("#StartDate").val());
            $("#txtEndDate").val($("#EndDate").val());
            $("#btnSubmit").click();
        } else
            alert("No data Found");

    }
</script>

ESS Web Application/Views/Request/EmployeeAttendanceReport.cshtml
@using ReportViewerForMvc;
@{
    ViewBag.Title = "EmployeeAttendanceReport";
}
<br />
<br />

@Html.ReportViewer(ViewBag.ReportViewer as Microsoft.Reporting.WebForms.ReportViewer)

ESS Web Application/Views/Request/EmployeeDetail.cshtml
@{
    ViewBag.Title = "EmployeeDetail";
}

<div class="block-header">
    <div class="row">
        <div class="col-lg-6 col-md-8 col-sm-12">
            <h2><a href="javascript:void(0);" class="btn btn-xs btn-link btn-toggle-fullwidth"><i class="fa fa-arrow-left"></i></a> Dashboard</h2>
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html"><i class="icon-home"></i></a></li>
                <li class="breadcrumb-item active">Dashboard</li>
            </ul>
        </div>

    </div>
</div>
<div class="row">
    <div class="col-lg-12 col-md-12">
        <div class="card">
            <div class="header">
                <h2>Employee Details</h2>
            </div>
            <div class="body">
                <div class="table-responsive">
                    <div class="col-md-6 col-sm-12">
                        <label>Department</label>
                        <div class="form-group">
                            <select id="Department" onchange="DepartmentSelect()" class="form-control show-tick">
                                <option value="0">Select Department</option>
                                @foreach (var item in ViewBag.Type)
                                {
                                    <option value="@item.Value">@item.Text</option>
                                }
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <label>Employee</label>
                        <div class="form-group">
                            <select id="Emp" class="form-control show-tick">
                                <option value="0">Select Employee</option>
                                @foreach (var item in ViewBag.User)
                                {
                                    if (item.Text == "Self")
                                    {
                                        <option selected value="@item.Value">@item.Text</option>
                                    }
                                    else
                                    {
                                        <option value="@item.Value">@item.Text</option>
                                    }
                                }
                            </select>
                        </div>
                    </div>
                    <br />
                    <div class="col-12">
                        <button onclick="Search()" type="submit" class="btn btn-primary">Generate Report</button>
                    </div>
                    <br />
                </div>
            </div>
        </div>
    </div>
</div>
@using (Html.BeginForm("EmployeeDetailReport", "Request", FormMethod.Post, new { target = "_blank" }))
{
    <input type="hidden" id="employeeId" name="EmpId" />
    <input type="hidden" id="DepartmentId" name="DepId" />
    <input type="submit" class="hidden" id="btnSubmit" hidden value="Export" />
}
<script>
    function Search() {
        if ($("#Emp").val() != undefined && $("#Emp").val() != null) {
            $("#employeeId").val($("#Emp").val());
            $("#DepartmentId").val($("#Department").val());
            $("#btnSubmit").click();
        } else
            alert("No data Found");
    }
    function DepartmentSelect() {
        $("#Emp").val("");
        var DepId = $("#Department option:selected").val();
        $.ajax({
            type: "Post",
            url: "/Request/GetUserByDepartment",
            data: { DepId: DepId },
            success: function (data) {
                var User = '';
                for (var i = 0; i < data.length; i++) {
                    User += '<option value="' + data[i].Value + '">' + data[i].Text + '</option>';
                }
                $("#Emp").html(User);
                if (data.length == 0)
                    $("#Emp").html('<option value="0">Select Employee </option>');
            }
        });
    }
</script>

ESS Web Application/Views/Request/LeaveDetail.cshtml
@{
    ViewBag.Title = "LeaveDetail";
}

<div class="block-header">
    <div class="row">
        <div class="col-lg-6 col-md-8 col-sm-12">
            <h2><a href="javascript:void(0);" class="btn btn-xs btn-link btn-toggle-fullwidth"><i class="fa fa-arrow-left"></i></a> Dashboard</h2>
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html"><i class="icon-home"></i></a></li>
                <li class="breadcrumb-item active">Dashboard</li>
            </ul>
        </div>

    </div>
</div>
<div class="row">
    <div class="col-lg-12 col-md-12">
        <div class="card">
            <div class="header">
                <h2>Leave Detail</h2>
            </div>
            <div class="body">
                <div class="table-responsive">
                    <div class="col-md-6 col-sm-12">
                        <label>Department</label>
                        <div class="form-group">
                            <select id="Department" onchange="DepartmentSelect()" class="form-control show-tick">
                                <option value="0">Select Department</option>
                                @foreach (var item in ViewBag.Type)
                                {
                                    <option value="@item.Value">@item.Text</option>
                                }
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <label>Employee</label>
                        <div class="form-group">
                            <select id="Emp" class="form-control show-tick">
                                <option value="0">Select Employee</option>
                                @foreach (var item in ViewBag.User)
                                {
                                    if (item.Text == "Self")
                                    {
                                        <option selected value="@item.Value">@item.Text</option>
                                    }
                                    else
                                    {
                                        <option value="@item.Value">@item.Text</option>
                                    }
                                }
                            </select>
                        </div>
                    </div>
                    <br />
                    <div class="col-12">
                        <button onclick="Search()" type="submit" class="btn btn-primary">Generate Report</button>
                    </div>
                    <br />
                </div>

            </div>
        </div>
    </div>
</div>
@using (Html.BeginForm("LeaveDetailReport", "Request", FormMethod.Post, new { target = "_blank" }))
{
    <input type="hidden" id="DepartmentId" name="DepId" />
    <input type="hidden" id="employeeId" name="EmpId" />
    <input type="submit" class="hidden" id="btnSubmit" hidden value="Export" />
}
<script>
    function Search() {
        if ($("#Emp").val() != undefined && $("#Emp").val() != null) {
            $("#employeeId").val($("#Emp").val());
            $("#DepartmentId").val($("#Department").val());
            $("#btnSubmit").click();
        } else
            alert("No data Found");
    }
    function DepartmentSelect() {
        $("#Emp").val("");
        var DepId = $("#Department option:selected").val();
        $.ajax({
            type: "Post",
            url: "/Request/GetUserByDepartment",
            data: { DepId: DepId },
            success: function (data) {
                var User = '';
                for (var i = 0; i < data.length; i++) {
                    User += '<option value="' + data[i].Value + '">' + data[i].Text + '</option>';
                }
                $("#Emp").html(User);
                if (data.length == 0)
                    $("#Emp").html('<option value="0">Select Employee </option>');
            }
        });
    }
</script>

ESS Web Application/Views/Request/LeaveDetailReport.cshtml
@using ReportViewerForMvc;
@{
    ViewBag.Title = "LeaveDetailReport";
}
<br />
<br />

@Html.ReportViewer(ViewBag.ReportViewer as Microsoft.Reporting.WebForms.ReportViewer)

ESS Web Application/Views/Request/ReimbursementDetailReport.cshtml
@using ReportViewerForMvc;
@{
    ViewBag.Title = "ReimbursementDetailReport";
}
<br />
<br />

@Html.ReportViewer(ViewBag.ReportViewer as Microsoft.Reporting.WebForms.ReportViewer)